"""
Phase 6 Regression Lock — Precision Drift Detection
=====================================================

These tests lock Long-EZ physics outputs to the externally-validated calibrated values
from Phase 5's accuracy report. Each locked value traces back through a chain of
external references:

    test_regression_lock.py
        -> data/validation/accuracy_report.json  (Phase 5 calibration result)
            -> data/validation/reference_data.json  (RAF CP-29/CP-31, wind tunnel data)

PURPOSE:
  Break the self-referential loop. Physics baselines previously generated by the same
  code being tested (physics_baseline.json) cannot catch regressions. These tests use
  the Phase 5 calibrated values — which were graded against external reference data —
  as their locked baselines.

WHAT THESE TESTS CATCH:
  Future code changes that cause physics outputs to drift outside the calibrated bounds:
  - Geometry parameter changes that shift NP/CG positions
  - Config changes that alter CLmax, alpha_0L, or gross weight
  - Algorithm changes that alter stall speed calculation

TWO-TIER ASSERTION PATTERN:
  Each test makes two assertions:
    1. External truth check: computed value within reference_data.json tolerance of the
       published/measured reference value. Catches gross errors.
    2. Drift detection check: computed value within a TIGHT tolerance of the Phase 5
       calibrated value. Catches code regressions even when still within external tolerance.

  The drift tolerances (0.01" for FS, 0.5 KTAS for speed) are much tighter than the
  reference tolerances (2.0" / 1.0" for FS, 5.0 KTAS for speed). This is the key
  innovation: reference tolerances catch physics errors, drift tolerances catch code changes.

LOCKED VALUES (DO NOT UPDATE unless re-calibrating against external reference data):
  All locked values come from data/validation/accuracy_report.json, generated 2026-03-13.
  Updating these constants without re-running calibration against external reference data
  would destroy the traceability chain and defeat the purpose of these tests.

EXCLUDED METRICS (known convention gaps, not locked):
  - static_margin_pct: FAIL in accuracy report (convention difference, not physics error)
  - empty_weight_lb: FAIL in accuracy report (partial structural model)
  - wing_area_sqft: FAIL in accuracy report (full planform vs. RAF semi-panel convention)
"""

import json
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from unittest.mock import MagicMock  # noqa: E402

sys.modules.setdefault("cadquery", MagicMock())
sys.modules.setdefault("OCP", MagicMock())

import pytest  # noqa: E402

from config import config  # noqa: E402

# ---------------------------------------------------------------------------
# Data file paths
# ---------------------------------------------------------------------------

ACCURACY_REPORT_PATH = REPO_ROOT / "data" / "validation" / "accuracy_report.json"
REF_DATA_PATH = REPO_ROOT / "data" / "validation" / "reference_data.json"


def _load_accuracy_report() -> dict:
    """Load accuracy_report.json — Phase 5 calibration result."""
    with open(ACCURACY_REPORT_PATH) as f:
        return json.load(f)


def _load_ref_data() -> dict:
    """Load reference_data.json — external published/measured reference."""
    with open(REF_DATA_PATH) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Locked Phase 5 calibrated values — from data/validation/accuracy_report.json
# (generated 2026-03-13, all PASS metrics trace to reference_data.json)
#
# DO NOT UPDATE unless re-calibrating against external reference data.
# Changing these values without re-running calibration against external
# reference data destroys the traceability chain.
# ---------------------------------------------------------------------------

# Phase 5 calibrated values — from data/validation/accuracy_report.json (2026-03-13)
# Each traces to reference_data.json (RAF CP-29, wind tunnel data)
# DO NOT UPDATE unless re-calibrating against external reference data
LOCKED_NP_PUBLISHED = 108.0007       # accuracy_report neutral_point_fs.computed
LOCKED_CG_FWD_PUBLISHED = 98.999     # accuracy_report cg_range_fwd_fs.computed
LOCKED_CG_AFT_PUBLISHED = 103.9994   # accuracy_report cg_range_aft_fs.computed
LOCKED_STALL_KTAS = 53.2867          # accuracy_report stall_speed_ktas.computed

# Config values — locked to prevent accidental modification; exact matches expected
LOCKED_GROSS_WEIGHT_LB = 1425.0      # accuracy_report max_gross_weight_lb.computed
LOCKED_CANARD_CLMAX = 1.35           # accuracy_report canard_clmax.computed
LOCKED_WING_CLMAX = 1.45             # accuracy_report wing_clmax.computed
LOCKED_CANARD_ALPHA_0L_DEG = -3.0    # accuracy_report canard_alpha_0l_deg.computed
LOCKED_WING_ALPHA_0L_DEG = -2.0      # accuracy_report wing_alpha_0l_deg.computed

# Drift detection tolerances (much tighter than external reference tolerances)
DRIFT_TOLERANCE_FS_IN = 0.01         # inches — catches sub-millimeter FS drift
DRIFT_TOLERANCE_SPEED_KTAS = 0.5     # knots — catches minor stall speed drift


# ---------------------------------------------------------------------------
# Helper: compute stall speed using same first-principles method as accuracy report
# ---------------------------------------------------------------------------

def _compute_stall_ktas(ref_data: dict) -> float:
    """Replicate the stall speed calculation from generate_accuracy_report.py.

    Uses published reference areas (NOT config areas) per accuracy_report convention_note.
    Published areas: wing=94.2 sqft + canard=15.6 sqft = 109.8 sqft total.
    """
    wing_area_sqft = ref_data["aircraft_specs"]["wing_area_sqft"]["value"]     # 94.2 sqft
    canard_area_sqft = ref_data["aircraft_specs"]["canard_area_sqft"]["value"]  # 15.6 sqft
    total_area_sqft = wing_area_sqft + canard_area_sqft                         # 109.8 sqft

    W = config.flight_condition.gross_weight_lb                                 # 1425 lb
    rho = 0.002377      # slug/ft^3 (sea-level standard atmosphere)
    S = total_area_sqft
    cl_max = config.aero_limits.canard_clmax                                    # 1.35

    v_fps = math.sqrt(2.0 * W / (rho * S * cl_max))
    v_ktas = v_fps / 1.6878     # 1 knot = 1.6878 ft/s
    return v_ktas


# ---------------------------------------------------------------------------
# Regression tests: stability metrics (NP, CG fwd, CG aft)
# ---------------------------------------------------------------------------


def test_regression_neutral_point():
    """REGRESSION LOCK: Neutral point (published datum) locked to Phase 5 calibrated value.

    External truth: must be within 2.0" of published 108.0" (RAF CP-29).
    Drift detection: must be within 0.01" of Phase 5 calibrated value 108.0007".

    Traces: accuracy_report.json neutral_point_fs.computed -> reference_data.json
            aircraft_specs.neutral_point_fs.value (RAF CP-29, p.18).
    """
    from core.analysis import PhysicsEngine

    ref_data = _load_ref_data()
    ref_np = ref_data["aircraft_specs"]["neutral_point_fs"]["value"]              # 108.0
    ref_tolerance = ref_data["aircraft_specs"]["neutral_point_fs"]["tolerance_abs"]  # 2.0

    engine = PhysicsEngine()
    metrics = engine.calculate_cg_envelope()
    computed_np_published = config.geometry.to_published_datum(metrics.neutral_point)

    # External truth check: within reference_data.json tolerance
    delta_from_ref = abs(computed_np_published - ref_np)
    assert delta_from_ref <= ref_tolerance, (
        f"REGRESSION: NP external truth check FAILED. "
        f"Computed NP = {computed_np_published:.4f}\" (published datum), "
        f"reference = {ref_np:.1f}\", delta = {delta_from_ref:.4f}\" "
        f"exceeds {ref_tolerance:.1f}\" tolerance (RAF CP-29). "
        f"Physics model has drifted outside validated bounds."
    )

    # Drift detection check: within tight tolerance of Phase 5 calibrated value
    delta_from_locked = abs(computed_np_published - LOCKED_NP_PUBLISHED)
    assert delta_from_locked <= DRIFT_TOLERANCE_FS_IN, (
        f"REGRESSION: NP drift detected. "
        f"Computed NP = {computed_np_published:.4f}\" (published datum), "
        f"Phase 5 locked value = {LOCKED_NP_PUBLISHED:.4f}\", "
        f"drift = {delta_from_locked:.6f}\" exceeds {DRIFT_TOLERANCE_FS_IN:.2f}\" tolerance. "
        f"If this is intentional, re-run Phase 5 calibration before updating locked value. "
        f"DO NOT update LOCKED_NP_PUBLISHED without re-calibrating against external data."
    )


def test_regression_cg_fwd():
    """REGRESSION LOCK: Forward CG limit (published datum) locked to Phase 5 calibrated value.

    External truth: must be within 1.0" of published 99.0" (RAF CP-29).
    Drift detection: must be within 0.01" of Phase 5 calibrated value 98.999".

    Traces: accuracy_report.json cg_range_fwd_fs.computed -> reference_data.json
            aircraft_specs.cg_range_fwd_fs.value (RAF CP-29, p.13).
    """
    from core.analysis import PhysicsEngine

    ref_data = _load_ref_data()
    ref_cg_fwd = ref_data["aircraft_specs"]["cg_range_fwd_fs"]["value"]              # 99.0
    ref_tolerance = ref_data["aircraft_specs"]["cg_range_fwd_fs"]["tolerance_abs"]   # 1.0

    engine = PhysicsEngine()
    metrics = engine.calculate_cg_envelope()
    computed_cg_fwd_published = config.geometry.to_published_datum(metrics.cg_range_fwd)

    # External truth check
    delta_from_ref = abs(computed_cg_fwd_published - ref_cg_fwd)
    assert delta_from_ref <= ref_tolerance, (
        f"REGRESSION: CG fwd external truth check FAILED. "
        f"Computed CG fwd = {computed_cg_fwd_published:.4f}\" (published datum), "
        f"reference = {ref_cg_fwd:.1f}\", delta = {delta_from_ref:.4f}\" "
        f"exceeds {ref_tolerance:.1f}\" tolerance (RAF CP-29). "
        f"Physics model has drifted outside validated bounds."
    )

    # Drift detection check
    delta_from_locked = abs(computed_cg_fwd_published - LOCKED_CG_FWD_PUBLISHED)
    assert delta_from_locked <= DRIFT_TOLERANCE_FS_IN, (
        f"REGRESSION: CG fwd drift detected. "
        f"Computed CG fwd = {computed_cg_fwd_published:.4f}\" (published datum), "
        f"Phase 5 locked value = {LOCKED_CG_FWD_PUBLISHED:.4f}\", "
        f"drift = {delta_from_locked:.6f}\" exceeds {DRIFT_TOLERANCE_FS_IN:.2f}\" tolerance. "
        f"If intentional, re-run Phase 5 calibration before updating locked value."
    )


def test_regression_cg_aft():
    """REGRESSION LOCK: Aft CG limit (published datum) locked to Phase 5 calibrated value.

    External truth: must be within 1.0" of published 104.0" (RAF CP-29).
    Drift detection: must be within 0.01" of Phase 5 calibrated value 103.9994".

    Traces: accuracy_report.json cg_range_aft_fs.computed -> reference_data.json
            aircraft_specs.cg_range_aft_fs.value (RAF CP-29, p.13).
    """
    from core.analysis import PhysicsEngine

    ref_data = _load_ref_data()
    ref_cg_aft = ref_data["aircraft_specs"]["cg_range_aft_fs"]["value"]              # 104.0
    ref_tolerance = ref_data["aircraft_specs"]["cg_range_aft_fs"]["tolerance_abs"]   # 1.0

    engine = PhysicsEngine()
    metrics = engine.calculate_cg_envelope()
    computed_cg_aft_published = config.geometry.to_published_datum(metrics.cg_range_aft)

    # External truth check
    delta_from_ref = abs(computed_cg_aft_published - ref_cg_aft)
    assert delta_from_ref <= ref_tolerance, (
        f"REGRESSION: CG aft external truth check FAILED. "
        f"Computed CG aft = {computed_cg_aft_published:.4f}\" (published datum), "
        f"reference = {ref_cg_aft:.1f}\", delta = {delta_from_ref:.4f}\" "
        f"exceeds {ref_tolerance:.1f}\" tolerance (RAF CP-29). "
        f"Physics model has drifted outside validated bounds."
    )

    # Drift detection check
    delta_from_locked = abs(computed_cg_aft_published - LOCKED_CG_AFT_PUBLISHED)
    assert delta_from_locked <= DRIFT_TOLERANCE_FS_IN, (
        f"REGRESSION: CG aft drift detected. "
        f"Computed CG aft = {computed_cg_aft_published:.4f}\" (published datum), "
        f"Phase 5 locked value = {LOCKED_CG_AFT_PUBLISHED:.4f}\", "
        f"drift = {delta_from_locked:.6f}\" exceeds {DRIFT_TOLERANCE_FS_IN:.2f}\" tolerance. "
        f"If intentional, re-run Phase 5 calibration before updating locked value."
    )


# ---------------------------------------------------------------------------
# Regression tests: performance (stall speed, gross weight)
# ---------------------------------------------------------------------------


def test_regression_stall_speed():
    """REGRESSION LOCK: Stall speed locked to Phase 5 calibrated value.

    External truth: must be within 5.0 KTAS of published 56 KTAS (RAF CP-29).
    Drift detection: must be within 0.5 KTAS of Phase 5 calibrated value 53.2867 KTAS.

    Calculation: first-principles using published reference areas (94.2 + 15.6 sqft)
    and canard CLmax (1.35) — canard stalls first in canard configuration.

    Traces: accuracy_report.json stall_speed_ktas.computed -> reference_data.json
            aircraft_specs.stall_speed_ktas.value (RAF CP-29, p.20).
    """
    ref_data = _load_ref_data()
    ref_stall_ktas = ref_data["aircraft_specs"]["stall_speed_ktas"]["value"]         # 56
    ref_tolerance = ref_data["aircraft_specs"]["stall_speed_ktas"]["tolerance_abs"]  # 5.0

    computed_stall_ktas = _compute_stall_ktas(ref_data)

    # External truth check
    delta_from_ref = abs(computed_stall_ktas - ref_stall_ktas)
    assert delta_from_ref <= ref_tolerance, (
        f"REGRESSION: Stall speed external truth check FAILED. "
        f"Computed V_stall = {computed_stall_ktas:.4f} KTAS, "
        f"published = {ref_stall_ktas} KTAS, "
        f"delta = {delta_from_ref:.4f} KTAS exceeds {ref_tolerance:.1f} KTAS tolerance. "
        f"Uses published areas: 94.2 + 15.6 = 109.8 sqft (NOT config areas). "
        f"Physics model has drifted outside validated bounds."
    )

    # Drift detection check
    delta_from_locked = abs(computed_stall_ktas - LOCKED_STALL_KTAS)
    assert delta_from_locked <= DRIFT_TOLERANCE_SPEED_KTAS, (
        f"REGRESSION: Stall speed drift detected. "
        f"Computed V_stall = {computed_stall_ktas:.4f} KTAS, "
        f"Phase 5 locked value = {LOCKED_STALL_KTAS:.4f} KTAS, "
        f"drift = {delta_from_locked:.4f} KTAS exceeds {DRIFT_TOLERANCE_SPEED_KTAS:.1f} KTAS tolerance. "
        f"If intentional, re-run Phase 5 calibration before updating LOCKED_STALL_KTAS. "
        f"Note: stall speed formula depends on config.aero_limits.canard_clmax and "
        f"config.flight_condition.gross_weight_lb — changes to either will trigger this."
    )


def test_regression_max_gross_weight():
    """REGRESSION LOCK: Max gross weight must exactly equal Phase 5 calibrated value 1425.0 lb.

    No tolerance — this is an FAA-approved hard regulatory limit. Exact match required.
    Also serves as regression lock ensuring config is not accidentally modified.

    Traces: accuracy_report.json max_gross_weight_lb.computed -> reference_data.json
            aircraft_specs.max_gross_weight_lb.value (RAF CP-29, p.12).
    """
    computed_gross_weight = config.flight_condition.gross_weight_lb

    assert computed_gross_weight == LOCKED_GROSS_WEIGHT_LB, (
        f"REGRESSION: Max gross weight changed. "
        f"config.flight_condition.gross_weight_lb = {computed_gross_weight} lb, "
        f"Phase 5 locked value = {LOCKED_GROSS_WEIGHT_LB} lb. "
        f"FAA-approved max gross weight for Long-EZ Model 61 is a hard regulatory limit. "
        f"This must be an exact match — 1425.0 lb per RAF CP-29, p.12."
    )


# ---------------------------------------------------------------------------
# Regression tests: airfoil aerodynamic limits (config vs. wind tunnel)
# ---------------------------------------------------------------------------


def test_regression_canard_clmax():
    """REGRESSION LOCK: Canard CLmax locked to Phase 5 calibrated value.

    External truth: must be within 0.05 of Roncz R1145MS wind tunnel value 1.35.
    Direct config read — tests that config.aero_limits.canard_clmax is not changed.

    Traces: accuracy_report.json canard_clmax.computed -> reference_data.json
            airfoil_data.roncz_r1145ms.cl_max.value (Purdue wind tunnel, 1984).
    """
    ref_data = _load_ref_data()
    ref_clmax = ref_data["airfoil_data"]["roncz_r1145ms"]["cl_max"]["value"]  # 1.35
    ref_tolerance = 0.05  # from accuracy_report tolerance_abs

    computed_clmax = config.aero_limits.canard_clmax

    # External truth check (also serves as drift lock — tolerance is already tight)
    delta = abs(computed_clmax - ref_clmax)
    assert delta <= ref_tolerance, (
        f"REGRESSION: Canard CLmax external truth check FAILED. "
        f"config.aero_limits.canard_clmax = {computed_clmax:.3f}, "
        f"Roncz R1145MS wind tunnel = {ref_clmax:.3f}, "
        f"delta = {delta:.4f} exceeds {ref_tolerance:.2f} tolerance. "
        f"Safety-critical: canard CLmax controls stall characteristics. "
        f"Source: Roncz R1145MS wind tunnel report, Purdue 1984."
    )

    # Drift detection: exact match to Phase 5 locked value (config value, should not change)
    assert computed_clmax == LOCKED_CANARD_CLMAX, (
        f"REGRESSION: Canard CLmax drift from Phase 5 value. "
        f"config.aero_limits.canard_clmax = {computed_clmax:.4f}, "
        f"Phase 5 locked value = {LOCKED_CANARD_CLMAX:.4f}. "
        f"Config value should not change without deliberate calibration update. "
        f"If intentional, re-run Phase 5 calibration before updating LOCKED_CANARD_CLMAX."
    )


def test_regression_wing_clmax():
    """REGRESSION LOCK: Wing CLmax locked to Phase 5 calibrated value.

    External truth: must be within 0.05 of Eppler 1230 wind tunnel value 1.45.
    Direct config read — tests that config.aero_limits.wing_clmax is not changed.

    Traces: accuracy_report.json wing_clmax.computed -> reference_data.json
            airfoil_data.eppler_1230.cl_max.value (Stuttgart/UIUC database).
    """
    ref_data = _load_ref_data()
    ref_clmax = ref_data["airfoil_data"]["eppler_1230"]["cl_max"]["value"]  # 1.45
    ref_tolerance = 0.05  # from accuracy_report tolerance_abs

    computed_clmax = config.aero_limits.wing_clmax

    # External truth check
    delta = abs(computed_clmax - ref_clmax)
    assert delta <= ref_tolerance, (
        f"REGRESSION: Wing CLmax external truth check FAILED. "
        f"config.aero_limits.wing_clmax = {computed_clmax:.3f}, "
        f"Eppler 1230 wind tunnel = {ref_clmax:.3f}, "
        f"delta = {delta:.4f} exceeds {ref_tolerance:.2f} tolerance. "
        f"Source: Eppler 1230 UIUC database, Stuttgart/Eppler reports."
    )

    # Drift detection: exact match to Phase 5 locked value
    assert computed_clmax == LOCKED_WING_CLMAX, (
        f"REGRESSION: Wing CLmax drift from Phase 5 value. "
        f"config.aero_limits.wing_clmax = {computed_clmax:.4f}, "
        f"Phase 5 locked value = {LOCKED_WING_CLMAX:.4f}. "
        f"Config value should not change without deliberate calibration update."
    )


def test_regression_canard_alpha_0l():
    """REGRESSION LOCK: Canard zero-lift angle of attack locked to Phase 5 calibrated value.

    External truth: must be within 0.5 deg of Roncz R1145MS wind tunnel value -3.0 deg.
    Direct config read — tests that config.aero_limits.canard_alpha_0L is not changed.

    Traces: accuracy_report.json canard_alpha_0l_deg.computed -> reference_data.json
            airfoil_data.roncz_r1145ms.alpha_zero_lift_deg.value (Purdue wind tunnel, 1984).
    """
    ref_data = _load_ref_data()
    ref_alpha = ref_data["airfoil_data"]["roncz_r1145ms"]["alpha_zero_lift_deg"]["value"]  # -3.0
    ref_tolerance = 0.5  # degrees, from accuracy_report tolerance_abs

    computed_alpha = config.aero_limits.canard_alpha_0L

    # External truth check
    delta = abs(computed_alpha - ref_alpha)
    assert delta <= ref_tolerance, (
        f"REGRESSION: Canard alpha_0L external truth check FAILED. "
        f"config.aero_limits.canard_alpha_0L = {computed_alpha:.2f} deg, "
        f"Roncz R1145MS wind tunnel = {ref_alpha:.2f} deg, "
        f"delta = {delta:.3f} deg exceeds {ref_tolerance:.1f} deg tolerance. "
        f"Source: Roncz R1145MS wind tunnel report, Purdue 1984."
    )

    # Drift detection: exact match to Phase 5 locked value
    assert computed_alpha == LOCKED_CANARD_ALPHA_0L_DEG, (
        f"REGRESSION: Canard alpha_0L drift from Phase 5 value. "
        f"config.aero_limits.canard_alpha_0L = {computed_alpha:.4f} deg, "
        f"Phase 5 locked value = {LOCKED_CANARD_ALPHA_0L_DEG:.4f} deg. "
        f"Config value should not change without deliberate calibration update."
    )


def test_regression_wing_alpha_0l():
    """REGRESSION LOCK: Wing zero-lift angle of attack locked to Phase 5 calibrated value.

    External truth: must be within 0.5 deg of Eppler 1230 wind tunnel value -2.0 deg.
    Direct config read — tests that config.aero_limits.wing_alpha_0L is not changed.

    Traces: accuracy_report.json wing_alpha_0l_deg.computed -> reference_data.json
            airfoil_data.eppler_1230.alpha_zero_lift_deg.value (Stuttgart/UIUC database).
    """
    ref_data = _load_ref_data()
    ref_alpha = ref_data["airfoil_data"]["eppler_1230"]["alpha_zero_lift_deg"]["value"]  # -2.0
    ref_tolerance = 0.5  # degrees, from accuracy_report tolerance_abs

    computed_alpha = config.aero_limits.wing_alpha_0L

    # External truth check
    delta = abs(computed_alpha - ref_alpha)
    assert delta <= ref_tolerance, (
        f"REGRESSION: Wing alpha_0L external truth check FAILED. "
        f"config.aero_limits.wing_alpha_0L = {computed_alpha:.2f} deg, "
        f"Eppler 1230 wind tunnel = {ref_alpha:.2f} deg, "
        f"delta = {delta:.3f} deg exceeds {ref_tolerance:.1f} deg tolerance. "
        f"Source: Eppler 1230 UIUC database, Stuttgart/Eppler reports."
    )

    # Drift detection: exact match to Phase 5 locked value
    assert computed_alpha == LOCKED_WING_ALPHA_0L_DEG, (
        f"REGRESSION: Wing alpha_0L drift from Phase 5 value. "
        f"config.aero_limits.wing_alpha_0L = {computed_alpha:.4f} deg, "
        f"Phase 5 locked value = {LOCKED_WING_ALPHA_0L_DEG:.4f} deg. "
        f"Config value should not change without deliberate calibration update."
    )


# ---------------------------------------------------------------------------
# Traceability tests: verify no self-referential data sources
# ---------------------------------------------------------------------------


def test_regression_baselines_not_self_referential():
    """TRACEABILITY: This test file must not load physics_baseline.json as a data source.

    physics_baseline.json is generated by the same code being tested — loading it
    as a data source creates a self-referential loop where tests can never catch
    regressions (the baseline updates with the code).

    This test reads its own source and confirms 'physics_baseline.json' does not
    appear as an import path, open() argument, or data source.

    Note: the string 'physics_baseline.json' may appear in this assertion itself
    or in comments — that is acceptable. Only data-loading usage is forbidden.
    """
    source_path = Path(__file__)
    source_text = source_path.read_text()

    # Find all lines that reference physics_baseline.json
    lines_with_baseline = [
        (i + 1, line.strip())
        for i, line in enumerate(source_text.splitlines())
        if "physics_baseline.json" in line
    ]

    # Lines that are acceptable: comments, docstrings, and this assertion itself
    # We check that no line is an actual data-loading operation (open, json.load, Path)
    forbidden_patterns = ["open(", "json.load", "Path(", "read_text", "read("]

    violations = []
    for lineno, line in lines_with_baseline:
        # Skip comment lines (start with #) and docstring content
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        if stripped.startswith('"""') or stripped.startswith("'''"):
            continue
        if stripped.startswith('"') or stripped.startswith("'"):
            # String literal (docstring continuation or assertion string)
            continue

        # Check if it's a data-loading operation
        for pattern in forbidden_patterns:
            if pattern in line:
                violations.append(f"  Line {lineno}: {line}")
                break

    assert not violations, (
        f"TRACEABILITY VIOLATION: test_regression_lock.py loads physics_baseline.json "
        f"as a data source. This creates a self-referential loop. "
        f"Remove these data-loading references:\n" + "\n".join(violations)
    )


def test_regression_values_match_accuracy_report():
    """TRACEABILITY: Locked constants in this file must match accuracy_report.json PASS metrics.

    Verifies that the LOCKED_* constants defined in this module exactly match the
    corresponding computed values in accuracy_report.json. This creates a documented
    traceability link: locked constants -> accuracy report -> reference_data.json.

    If this test fails, the locked constants are out of sync with the accuracy report
    and must be updated (along with re-running Phase 5 calibration if needed).
    """
    report = _load_accuracy_report()

    # Build lookup of metric_id -> computed value for PASS metrics only
    pass_metrics = {
        m["metric_id"]: m["computed"]
        for m in report["metrics"]
        if m["grade"] == "PASS"
    }

    expected_count = 9
    assert len(pass_metrics) == expected_count, (
        f"TRACEABILITY: Expected {expected_count} PASS metrics in accuracy_report.json, "
        f"found {len(pass_metrics)}. The report may have changed."
    )

    # Verify each locked constant against the report
    checks = [
        ("neutral_point_fs",      LOCKED_NP_PUBLISHED,        "LOCKED_NP_PUBLISHED"),
        ("cg_range_fwd_fs",       LOCKED_CG_FWD_PUBLISHED,    "LOCKED_CG_FWD_PUBLISHED"),
        ("cg_range_aft_fs",       LOCKED_CG_AFT_PUBLISHED,    "LOCKED_CG_AFT_PUBLISHED"),
        ("stall_speed_ktas",      LOCKED_STALL_KTAS,          "LOCKED_STALL_KTAS"),
        ("max_gross_weight_lb",   LOCKED_GROSS_WEIGHT_LB,     "LOCKED_GROSS_WEIGHT_LB"),
        ("canard_clmax",          LOCKED_CANARD_CLMAX,        "LOCKED_CANARD_CLMAX"),
        ("wing_clmax",            LOCKED_WING_CLMAX,          "LOCKED_WING_CLMAX"),
        ("canard_alpha_0l_deg",   LOCKED_CANARD_ALPHA_0L_DEG, "LOCKED_CANARD_ALPHA_0L_DEG"),
        ("wing_alpha_0l_deg",     LOCKED_WING_ALPHA_0L_DEG,   "LOCKED_WING_ALPHA_0L_DEG"),
    ]

    mismatches = []
    for metric_id, locked_value, const_name in checks:
        assert metric_id in pass_metrics, (
            f"TRACEABILITY: Metric '{metric_id}' not found in accuracy_report.json PASS metrics. "
            f"Report may have changed or metric grade is no longer PASS."
        )
        report_computed = pass_metrics[metric_id]
        if locked_value != report_computed:
            mismatches.append(
                f"  {const_name} = {locked_value!r} "
                f"!= accuracy_report['{metric_id}'].computed = {report_computed!r}"
            )

    assert not mismatches, (
        f"TRACEABILITY VIOLATION: Locked constants are out of sync with accuracy_report.json.\n"
        f"Update the LOCKED_* constants to match the report computed values:\n"
        + "\n".join(mismatches)
    )
