"""Physics regression test — validates against externally-validated accuracy report.

Phase 6: This test was rewired from the self-referential physics_baseline.json
to data/validation/accuracy_report.json. Every baseline value traces to
reference_data.json (published Long-EZ specs, wind tunnel data). No self-referential
sources are permitted (see generate_accuracy_report.validate_sources()).

Previous baseline (tests/snapshots/physics_baseline.json) contained values
generated by the same RegressionRunner code that validated against them — it
could never detect genuine regressions. This test catches real regressions.
"""

from pathlib import Path
import sys

# Ensure repository root on path for direct test execution
REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from core.simulation.regression import RegressionRunner, DEFAULT_ACCURACY_REPORT  # noqa: E402


def test_physics_regressions_match_accuracy_report(tmp_path):
    """Regression check: current physics outputs match Phase 5 calibrated values.

    Validates all PASS metrics from accuracy_report.json (9 of 12 metrics).
    FAIL metrics (static_margin_pct, empty_weight_lb, wing_area_sqft) are known
    convention differences, not regressions — they are excluded from this check.
    """
    runner = RegressionRunner(tolerance=0.05)
    passed, current, failures = runner.compare_to_accuracy_report(
        accuracy_report_path=DEFAULT_ACCURACY_REPORT, report_dir=tmp_path
    )
    assert passed, f"Physics regression failures vs accuracy report: {failures}"
    # Verify we checked at least 5 metrics (9 PASS metrics expected)
    assert len(current) >= 5, f"Expected at least 5 metrics, got {len(current)}"


def test_accuracy_report_pass_metrics_present(tmp_path):
    """Spot-check: key PASS metrics are present in current computed values."""
    import json

    runner = RegressionRunner(tolerance=0.05)
    passed, current, failures = runner.compare_to_accuracy_report(
        accuracy_report_path=DEFAULT_ACCURACY_REPORT, report_dir=tmp_path
    )
    # These PASS metrics must always be present
    assert "neutral_point_fs" in current, "neutral_point_fs missing from current run"
    assert "cg_range_fwd_fs" in current, "cg_range_fwd_fs missing from current run"
    assert "cg_range_aft_fs" in current, "cg_range_aft_fs missing from current run"
    assert "stall_speed_ktas" in current, "stall_speed_ktas missing from current run"
    assert "max_gross_weight_lb" in current, "max_gross_weight_lb missing from current run"
    assert "canard_clmax" in current, "canard_clmax missing from current run"


def test_regression_report_written(tmp_path):
    """Verify regression report JSON is written to report_dir."""
    runner = RegressionRunner(tolerance=0.05)
    runner.compare_to_accuracy_report(
        accuracy_report_path=DEFAULT_ACCURACY_REPORT, report_dir=tmp_path
    )
    report_file = tmp_path / "physics_accuracy_regression_report.json"
    assert report_file.exists(), "Regression report JSON was not written"

    import json
    with open(report_file) as f:
        report = json.load(f)
    assert "baseline_source" in report
    assert "current_values" in report
    assert "failures" in report
    assert report["status"] in ("pass", "fail")
