"""Physics regression scenarios anchored to configuration baselines."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Tuple

from config import config
from .fea_adapter import BeamFEAAdapter
from .openvsp_adapter import OpenVSPAdapter

# Phase 6: Default baseline is now the accuracy report (externally-validated)
# Every metric in this file traces to reference_data.json (published Long-EZ specs,
# wind tunnel data) — not to physics_baseline.json (self-referential).
DEFAULT_ACCURACY_REPORT = (
    Path(__file__).resolve().parents[2] / "data" / "validation" / "accuracy_report.json"
)


@dataclass
class ScenarioResult:
    name: str
    metrics: Dict[str, float]


@dataclass
class RegressionScenario:
    name: str
    description: str
    evaluate: Callable[[OpenVSPAdapter, BeamFEAAdapter], ScenarioResult]


class RegressionRunner:
    """Run deterministic physics regressions for CI validation."""

    def __init__(self, tolerance: float = 0.05):
        self.tolerance = tolerance
        self.aero = OpenVSPAdapter()
        self.fea = BeamFEAAdapter()
        # DEPRECATED SCENARIOS: These scenarios produce self-referential values
        # (they compared against physics_baseline.json which was generated by the
        # same code being tested). Retained for backward compatibility only.
        # Phase 6 uses compare_to_accuracy_report() instead, which compares against
        # externally-validated values from data/validation/accuracy_report.json.
        self.scenarios: List[RegressionScenario] = [
            RegressionScenario(
                name="wing_reflex_moment",
                description="[DEPRECATED] Pitching moment from wing reflex and canard incidence",
                evaluate=self._wing_reflex_moment,
            ),
            RegressionScenario(
                name="lift_curve_slope",
                description="[DEPRECATED] Lift-curve slope derived from VSPAERO polars",
                evaluate=self._lift_curve_slope,
            ),
            RegressionScenario(
                name="spar_tip_deflection",
                description="[DEPRECATED] Main spar tip deflection under representative gust load",
                evaluate=self._spar_tip_deflection,
            ),
        ]

    def _wing_reflex_moment(
        self, aero: OpenVSPAdapter, _: BeamFEAAdapter
    ) -> ScenarioResult:
        polars = aero.run_vspaero([0])
        cm0 = polars[0].cm if polars else 0.0
        washout = config.geometry.wing_washout
        metric = cm0 - 0.0005 * washout
        return ScenarioResult(
            name="wing_reflex_moment",
            metrics={"cm_at_trim": metric},
        )

    def _lift_curve_slope(
        self, aero: OpenVSPAdapter, _: BeamFEAAdapter
    ) -> ScenarioResult:
        slope = aero.lift_curve_slope([-4, 0])
        return ScenarioResult(
            name="lift_curve_slope",
            metrics={"cl_per_deg": slope},
        )

    def _spar_tip_deflection(
        self, _: OpenVSPAdapter, fea: BeamFEAAdapter
    ) -> ScenarioResult:
        spar = fea.nominal_spar_check()
        jig = fea.jig_flatness_check()
        combined_deflection = spar["tip_deflection_in"] + 0.1 * jig["tip_deflection_in"]
        return ScenarioResult(
            name="spar_tip_deflection",
            metrics={
                "tip_deflection_in": combined_deflection,
                "spar_stress_psi": spar["max_stress_psi"],
            },
        )

    def run(self) -> List[ScenarioResult]:
        """Execute all regression scenarios.

        DEPRECATED: These scenarios compare against self-referential
        physics_baseline.json values. Use compare_to_accuracy_report() instead.
        """

        results: List[ScenarioResult] = []
        for scenario in self.scenarios:
            results.append(scenario.evaluate(self.aero, self.fea))
        return results

    def to_serializable(
        self, results: Iterable[ScenarioResult]
    ) -> Dict[str, Dict[str, float]]:
        return {res.name: res.metrics for res in results}

    def load_baseline(self, baseline_path: Path) -> Dict[str, Dict[str, float]]:
        """DEPRECATED: Use compare_to_accuracy_report() instead.

        This method loads self-referential physics_baseline.json baselines.
        Retained for backward compatibility during Phase 6 transition.
        The values in physics_baseline.json were generated by the same
        RegressionRunner code that validated against them — they are NOT
        externally validated. See data/validation/accuracy_report.json for
        externally-validated baselines.
        """
        with open(baseline_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def compare_to_baseline(
        self,
        baseline_path: Path,
        report_dir: Path,
    ) -> Tuple[bool, Dict[str, Dict[str, float]], List[str]]:
        """DEPRECATED: Use compare_to_accuracy_report() instead.

        Compare regression results to stored baseline with tolerance.
        This method uses physics_baseline.json which contains self-referential
        values generated by the same code being tested. Retained for backward
        compatibility during Phase 6 transition.
        """

        report_dir.mkdir(parents=True, exist_ok=True)
        baseline = self.load_baseline(baseline_path)
        current = self.to_serializable(self.run())

        failures: List[str] = []
        for name, metrics in current.items():
            if name not in baseline:
                failures.append(f"Missing baseline for {name}")
                continue

            for metric_name, value in metrics.items():
                if metric_name not in baseline[name]:
                    failures.append(f"Missing baseline metric {metric_name} for {name}")
                    continue

                reference = baseline[name][metric_name]
                if reference == 0:
                    deviation = abs(value - reference)
                else:
                    deviation = abs(value - reference) / abs(reference)

                if deviation > self.tolerance:
                    failures.append(
                        f"{name}:{metric_name} deviated by {deviation:.2%} (value {value:.4f} vs {reference:.4f})"
                    )

        report = {
            "baseline": baseline,
            "current": current,
            "tolerance": self.tolerance,
            "failures": failures,
            "status": "fail" if failures else "pass",
        }

        json_report = report_dir / "physics_validation_report.json"
        with open(json_report, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)

        return (len(failures) == 0, current, failures)

    def compare_to_accuracy_report(
        self,
        accuracy_report_path: Path,
        report_dir: Path,
    ) -> Tuple[bool, Dict[str, float], List[str]]:
        """Compare current physics outputs against accuracy_report.json baselines.

        Unlike the old compare_to_baseline() (which compared against self-referential
        physics_baseline.json), this method compares against externally-validated
        values from the Phase 5 accuracy report. Each metric traces to
        reference_data.json (published Long-EZ specs, wind tunnel data).

        The comparison strategy:
        - Load PASS metrics from accuracy_report.json (FAIL metrics are known gaps,
          not regression targets)
        - Re-run collect_metrics() to get current computed values
        - Compare each current computed value against the accuracy report's stored
          computed value (the calibrated baseline) using each metric's tolerance_abs
        - Return (all_passed, current_values_dict, failure_messages)

        Args:
            accuracy_report_path: Path to accuracy_report.json.
            report_dir: Directory to write the regression report JSON.

        Returns:
            Tuple of (passed, current_values, failures) where:
                - passed: True if all PASS metrics are within tolerance
                - current_values: Dict of metric_id -> current computed value
                - failures: List of failure message strings
        """
        from unittest.mock import MagicMock
        import sys

        # CadQuery/OCP mock must be set before importing core analysis modules
        # (same pattern used in generate_accuracy_report.py)
        sys.modules.setdefault("cadquery", MagicMock())
        sys.modules.setdefault("OCP", MagicMock())

        from scripts.generate_accuracy_report import collect_metrics
        from core.analysis import PhysicsEngine

        report_dir.mkdir(parents=True, exist_ok=True)

        # Load accuracy_report.json (the externally-validated baseline)
        with open(accuracy_report_path, "r", encoding="utf-8") as f:
            accuracy_report = json.load(f)

        # Load reference_data.json (needed to re-run collect_metrics)
        ref_data_path = accuracy_report_path.parent / "reference_data.json"
        with open(ref_data_path, "r", encoding="utf-8") as f:
            ref_data = json.load(f)

        # Filter to PASS metrics only — FAIL metrics are known gaps, not regressions
        baseline_metrics = {
            m["metric_id"]: m
            for m in accuracy_report["metrics"]
            if m["grade"] == "PASS"
        }

        # Re-run physics engine to get current values
        engine = PhysicsEngine()
        current_metric_list = collect_metrics(ref_data, config, engine)
        current_values: Dict[str, float] = {
            m["metric_id"]: m["computed"] for m in current_metric_list
        }

        # Compare current values against calibrated baselines
        failures: List[str] = []
        for metric_id, baseline_m in baseline_metrics.items():
            if metric_id not in current_values:
                failures.append(f"Metric '{metric_id}' missing from current run")
                continue

            current_val = current_values[metric_id]
            baseline_val = baseline_m["computed"]  # calibrated baseline (Phase 5 run)
            tolerance_abs = baseline_m.get("tolerance_abs")

            if tolerance_abs is None:
                # Fall back to relative tolerance if no abs tolerance defined
                if baseline_val == 0:
                    deviation = abs(current_val - baseline_val)
                else:
                    deviation = abs(current_val - baseline_val) / abs(baseline_val)
                if deviation > self.tolerance:
                    failures.append(
                        f"{metric_id}: deviated by {deviation:.2%} "
                        f"(current {current_val:.4f} vs baseline {baseline_val:.4f})"
                    )
            else:
                error_abs = abs(current_val - baseline_val)
                if error_abs > tolerance_abs:
                    failures.append(
                        f"{metric_id}: abs error {error_abs:.6f} exceeds tolerance "
                        f"{tolerance_abs:.6f} "
                        f"(current {current_val:.4f} vs baseline {baseline_val:.4f})"
                    )

        # Write regression report
        regression_report = {
            "baseline_source": str(accuracy_report_path),
            "baseline_pass_metrics": list(baseline_metrics.keys()),
            "current_values": current_values,
            "tolerance": self.tolerance,
            "failures": failures,
            "status": "fail" if failures else "pass",
        }
        json_report = report_dir / "physics_accuracy_regression_report.json"
        with open(json_report, "w", encoding="utf-8") as f:
            json.dump(regression_report, f, indent=2)

        return (len(failures) == 0, current_values, failures)
