"""
Forge Knowledge Context Loader
==============================

Loads Forge knowledge synthesis exports (markdown) for programmatic access
within the Open-EZ PDE. These files are generated by the Forge pipeline at
~/forge and copied into data/ for offline reference.

Usage:
    from data.forge_context import forge_context

    # Get aviation knowledge as string
    aviation = forge_context.aviation

    # Get bridge notes (cross-domain connections)
    bridges = forge_context.bridges

    # Check what's available
    print(forge_context.available_topics)
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional

_DATA_DIR = Path(__file__).parent


@dataclass
class ForgeContext:
    """Lazy loader for Forge knowledge export markdown files."""

    _cache: Dict[str, str] = field(default_factory=dict, repr=False)

    # Map topic names to filenames
    TOPICS: Dict[str, str] = field(
        default_factory=lambda: {
            "aviation": "forge-aviation-context.md",
            "3dprinting": "forge-3dprinting-context.md",
            "bridges": "forge-bridges.md",
        },
        repr=False,
    )

    def _load(self, topic: str) -> Optional[str]:
        """Load a topic file, returning None if missing."""
        if topic in self._cache:
            return self._cache[topic]
        filename = self.TOPICS.get(topic)
        if not filename:
            return None
        path = _DATA_DIR / filename
        if not path.exists():
            return None
        text = path.read_text(encoding="utf-8")
        self._cache[topic] = text
        return text

    @property
    def aviation(self) -> Optional[str]:
        """Aviation context: canard aero, Long-EZ history, composites, flight testing."""
        return self._load("aviation")

    @property
    def printing(self) -> Optional[str]:
        """3D printing context: jigs, fixtures, CNC foam, composite tooling."""
        return self._load("3dprinting")

    @property
    def bridges(self) -> Optional[str]:
        """Bridge notes: cross-domain connections between aviation, composites, 3D printing."""
        return self._load("bridges")

    @property
    def available_topics(self) -> list[str]:
        """List topics that have files on disk."""
        return [
            topic
            for topic, filename in self.TOPICS.items()
            if (_DATA_DIR / filename).exists()
        ]

    def get(self, topic: str) -> Optional[str]:
        """Load any topic by name. Returns None if not found."""
        return self._load(topic)

    def search(self, query: str) -> Dict[str, list[str]]:
        """Simple keyword search across all available topics.

        Returns a dict of topic -> list of matching lines.
        """
        query_lower = query.lower()
        results: Dict[str, list[str]] = {}
        for topic in self.available_topics:
            content = self._load(topic)
            if content is None:
                continue
            matches = [
                line.strip()
                for line in content.splitlines()
                if query_lower in line.lower() and line.strip()
            ]
            if matches:
                results[topic] = matches
        return results


# Singleton - import this throughout the project
forge_context = ForgeContext()
